modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "${issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "${mod_logo}"

[[dependencies.igtips]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.igtips]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.igtips]]
modId = "architectury"
mandatory = true
versionRange = "[${depend_architectury},)"
ordering = "AFTER"
side = "BOTH"
